### ISSUE TITLE
♻️ Using Result object as control flow instead of exceptions

### ISSUE THREAD

**Issue by christoment** [SSWConsulting/SSW.CleanArchitecture#7] opened 2023-03-13 06:11 UTC
Premise:
- Exceptions are slower than Result objects (https://youtu.be/a1ye9eGTB98 - quick benchmark shows ~1us slower)
- Using Exceptions as a control flow is a questionable approach, since it allows code to jump from nested method all the way to the caller (questionable = both good and bad)
- Using result objects everywhere means more codes to write

Consideration:
- Using mixed method is a brain overload for a small performance benefit
- We haven't seen any big performance problems yet on our clients

Proposed decision:
- Keep using exceptions for now - keep it simple
- When there's a need arise (e.g. performance requirement, validation requirement) - handle it case-by-case

**Comment by Hona** [comment] 2023-03-13 07:57
TODO: @christoment write a rule + maybe CTF

**Comment by danielmackay** [comment] 2023-05-23 11:50
https://www.youtube.com/watch?v=YbuSuSpzee4

**Comment by danielmackay** [comment] 2024-10-21 04:11
Closing as this is a duplicate of #137

**Closed by danielmackay** 2024-10-21 04:11 UTC
